### ISSUE TITLE
No service for type IServiceProviderFactory<IServiceCollection> being thrown.

### ISSUE THREAD

**Issue by mskurnik** [ivaylokenov/MyTested.AspNetCore.Mvc#258]
Similar to #256, I am getting the following exception when attempting to run tests on all controllers.  I am guessing it is something to do with a DI but I don't know which one.
```
Result StackTrace:	
at MyTested.AspNetCore.Mvc.MyMvc.Controller[TController]()
...
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.<>c__DisplayClass0_0.<LoadMethods>b__0(IServiceCollection services)
   at MyTested.AspNetCore.Mvc.Internal.Application.TestApplication.PrepareServices(IServiceCollection serviceCollection, StartupMethods startupMethods)
   at MyTested.AspNetCore.Mvc.Internal.Application.TestApplication.Initialize()
   at MyTested.AspNetCore.Mvc.Internal.Application.TestApplication.TryInitialize()
   at MyTested.AspNetCore.Mvc.MyMvc..cctor()
Result Message:	
The type initializer for 'MyTested.AspNetCore.Mvc.MyMvc' threw an exception.
No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Microsoft.Extensions.DependencyInjection.IServiceCollection]' has been registered.
```

I tried adding `services.AddSingleton(sp => Mock.Of<IServiceCollection>());` to my `TestStartup.cs` class

**Comment by ivaylokenov** [comment]
@mskurnik Which version of ASP.NET Core MVC are you using?

Can I see your Startup.cs class? I believe you are using custom inversion of control container instead of the default one? If yes, I need to know which one so I can help.

In the next version of the testing framework this will be supported out of the box.

**Comment by mskurnik** [comment]
I am using version 2.1.0.  I am not using any IOC.

**Startup.cs**
```C#
public void ConfigureServices(IServiceCollection services)
{
	// Add framework services.
	services.AddDbContext<MyDbContext>(
		options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
		sqlOptions => sqlOptions.EnableRetryOnFailure()));

	// SQL configuration for non-injected dbcontext
	DbContextOptionsBuilder<MyDbContext> builder = new DbContextOptionsBuilder<MyDbContext>();
	builder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
	services.AddSingleton(builder.Options);

	// Identtity
	services.AddIdentity<ApplicationUser, IdentityRole>(
		options =>
		{
			...
		})
		.AddEntityFrameworkStores<MyDbContext>()
		.AddDefaultTokenProviders();
	
	services
		.AddMvc()
		.AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

	// Data Protection (app name for machine key)
	services.AddDataProtection().SetApplicationName("My Applicaiton");

	// View To String
	services.AddTransient<RazorViewToStringRenderer>();

	// Diagnostics
	DiagnosticListener diagnosticSource = new DiagnosticListener("MyApplication");
	services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();
	services.AddSingleton<DiagnosticSource>(diagnosticSource);

	// Add Kendo UI services to the services container
	services.AddKendo();
	
	// Add application services.
	services.AddTransient<IEmailSender, MessageServices>();
	services.AddTransient<ISmsSender, MessageServices>();
	services.Configure<MessageSenderOptions>(Configuration.GetSection("EmailSettings"));
	services.Configure<AmazonServiceConfig>(Configuration.GetSection("AWS"));

	// AWS
	services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
	services.AddAWSService<IAmazonS3>();
	
	// SignalR
	ConfigureSignalR(services);
}

private static void ConfigureSignalR(IServiceCollection services)
{
	services.AddSignalR(options => options.Hubs.EnableDetailedErrors = true);
	IServiceProvider provider = services.BuildServiceProvider();
	IConnectionManager connectionManager = provider.GetService<IConnectionManager>();
	services.AddSingleton(connectionManager.GetHubContext<AlphaHub>());
	services.AddSingleton(connectionManager.GetHubContext<BravoHub>());
	services.AddSingleton(connectionManager.GetHubContext<CharlieHub>());
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	loggerFactory.AddConsole(Configuration.GetSection("Logging"));
	loggerFactory.AddDebug();

	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
		app.UseDatabaseErrorPage();
		app.UseBrowserLink();
	}
	else
	{
		app.UseExceptionHandler("/Home/Error");
	}

	app.UseStaticFiles();

	// Authentication
	app.UseIdentity();

	// Kendo UI
	app.UseKendo(env);

	// SignalR
	app.UseSignalR();

	app.UseMvc(routes =>
	{
		routes.MapRoute("Admin", "{area:exists}/{controller}/{action=Index}/{id?}");
		routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
		routes.MapRoute("api", "api/{controller}/{id?}");
	});

	// Initialize Database
	PortalDbInitializer.Initialize(app.ApplicationServices);
}
```

**TestStartup.cs**
```C#
public TestStartup(IHostingEnvironment env) : base(env) { }

public void ConfigureTestServices(IServiceCollection services)
{
	ConfigureServices(services);

	IConfigurationBuilder builder = new ConfigurationBuilder()
		.SetBasePath(GetBaseDirectory())
		.AddJsonFile("appsettings.json", true, true)
		.AddUserSecrets()
		.AddEnvironmentVariables();

	services.ReplaceSingleton<SignInManager<ApplicationUser>, SignInManagerMock>();
	services.ReplaceSingleton<UserManager<ApplicationUser>, UserManagerMock>();
	services.ReplaceSingleton<RoleManager<IdentityRole>, RoleManagerMock>();
	services.ReplaceSingleton<MyDbContext, MyDbContextMock>();
	services.AddDbContext<MyDbContext>(options => options.UseSqlServer(builder.Build().GetConnectionString("DefaultConnection")));
	services.ReplaceSingleton<MyDbContext>(services.BuildServiceProvider().GetRequiredService<MyDbContext>());
	services.ReplaceSingleton<IHostingEnvironment>(new HostingEnvironment
	{
		ApplicationName = "MyApplication",
		ContentRootPath = AppContext.BaseDirectory,
		WebRootPath = GetWebDirectory(),
		EnvironmentName = "Development"
	});
	DbContextOptionsBuilder<MyDbContext> optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
	optionsBuilder.UseSqlServer(builder.Build().GetConnectionString("DefaultConnection"));
	services.ReplaceSingleton<DbContextOptions>(optionsBuilder.Options);
	
	// Trying to solve the issue
	services.AddSingleton(sp => Mock.Of<IServiceCollection>());
	services.AddSingleton(sp => Mock.Of<IServiceProviderFactory<IServiceCollection>>());
}
111

**Comment by ivaylokenov** [comment]
@mskurnik The `IServiceProviderFactory` interface is part of 1.1.0 (for reference here: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L54) which is not supported yet in the testing framework as it supports only version 1.0.1. I am currently migrating the library for the new version of the MVC framework (1.1.0), and it will be uploaded to NuGet by the end of the week. Is it OK for you to wait for that long?

Otherwise, we may workaround the problem by using a `ConfigureContainer` method, but I cannot promise that the library will have correct assertions while there is a version mismatch.

**Comment by mskurnik** [comment]
I can wait.  I just wanted you to at least know what was going on.

**Comment by ivaylokenov** [comment]
@mskurnik Thank you for that! I will let you know when the new version of the library is uploaded to NuGet.

**Comment by ivaylokenov** [comment]
@mskurnik All packages are now compatible with version 1.1.0 and are uploaded to NuGet. Thanks again! 👍

**Comment by mskurnik** [comment]
I can confirm that MyTested.* 1.1.0 packages on NuGet work with .NET Core 1.1.0.  Thank you!

**Comment by ivaylokenov** [comment]
@mskurnik You are very welcome! 👍
