### ISSUE TITLE
Calling Url.Action throws out of range exception.

### ISSUE THREAD

**Issue by mskurnik** [ivaylokenov/MyTested.AspNetCore.Mvc#263]
When calling Url.Action("Index", "Home") (or something similar) I get the following exception:

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper.get_Router()
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper.GetVirtualPathData(String routeName, RouteValueDictionary values)
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper.Action(UrlActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.UrlHelperExtensions.Action(IUrlHelper helper, String action, String controller, Object values, String protocol, String host, String fragment)
   at Microsoft.AspNetCore.Mvc.UrlHelperExtensions.Action(IUrlHelper helper, String action, String controller, Object values)
   at MyApplication.Areas.Admin.Controllers.UserController.<NotifyNewUser>d__15.MoveNext() in MyClass.cs:line 395
```

**Comment by ivaylokenov** [comment]
@mskurnik May I see the action code and the actual test. The exception is thrown because there are no routers attached to the `HttpContext` that is part of the controller. Try calling `WithRouteData()` before invoking `Calling()`.

**Comment by mskurnik** [comment]
Well that fixed it.  Thanks!

**Comment by ivaylokenov** [comment]
@mskurnik There is a special explicit check for this kind of exceptions: https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/blob/development/src/MyTested.AspNetCore.Mvc.Abstractions/Utilities/Validators/InvocationValidator.cs#L36

I wonder why you did not see the friendly error message but saw the argument out of range exception directly. I will leave the issue open for now so that I can fix it in a future version.

Do you have any sample code, which may help me debug the problem?

**Comment by mskurnik** [comment]
Nothing fancy.  I will provide code samples tomorrow.

**Comment by ivaylokenov** [comment]
@mskurnik I will be very thankful for that! 👍

**Comment by ivaylokenov** [comment]
@mskurnik Any updates?

**Comment by mskurnik** [comment]
I was never able to replicate this.
